### ISSUE TITLE
Visualization isn't properly working.

### ISSUE THREAD

**Issue by Tehtehteh** [homeaway/kibana#19]
**Kibana version**: 4.5.4 with Nested support

**Elasticsearch version**: 2.4.0

**Server OS version**:

**Browser version**: Chrome

**Browser OS version**:

**Original install method (e.g. download page, yum, from source, etc.)**: Npm form source

**Description of the problem including expected versus actual behavior**: I tried to create visualization using EXISTS syntax, but it makes "wrong" queries, matching whole document. For example, I have log in format of 
`log id : id,
users: [
{
    user_id: user_id, 
    user_won: 1 or 0,
    user_bid: integer
},
{
    user_id: user_id2, 
    user_won: 1 or 0,
    user_bid: integer
},
]
`
And problem is that whenever I try to make chart bar with average user_bid metric and with terms of user_id and with filter of user_won=1 it won't let me pass your query syntax, i.e. '* AND users.won=1'.

**Comment by ppadovani** [comment]
I will take a look at this in the next day or so.

**Comment by Tehtehteh** [comment]
Sorry for delay, I use this template-mapping and create indices via python script. Users property has user_id and user_bid and user_won properties. I can backup index and send it to you if you want.
`{
  "template": "rtb*_new",
  "mappings": {
    "map_csv": {
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "@version": {
          "type": "string",
          "index": "not_analyzed"
        },
        "id": {
            "type": "integer"
        }
        "country": {
          "type": "string",
          "index": "not_analyzed"
        },
        "users": {
          "type": "nested"
        }
      }
    }
  }
}`

**Comment by ppadovani** [comment]
ok... I know what is going on... this will take some time to resolve...

**Comment by Tehtehteh** [comment]
Can you please elaborate? Maybe it was my mistake ?

**Comment by ppadovani** [comment]
Not your mistake.. The issue lies in a nested array of objects. The query parser that generates the elasticsearch query was originally setup to create filtered queries against 1.X elasticsearch. This worked flawlessly as scoring was turned off for the entire query. In elasticsearch 2.x version of my parser, I removed the filtered query as it was deprecated. When I tested, I mistakenly tested against data sets that didn't, or had few, arrays of nested objects. I did not see the query generation issue then. 

What I need to do is update the parser to properly generate filters for nested fields such that the proper data is returned. This will take some time..

**Comment by Tehtehteh** [comment]
Oh, I see now. I can provide you with log examples/index backup to test this. Thanks again for your fork.

**Comment by ppadovani** [comment]
Ok... so I believe I've fixed the query part of this issue... 

1. The EXISTS <expr> of the query (my language) now will induce a 'filter' on the nested expression. 
2. A NOT EXISTS <expr> will induce a 'must_not' of the nested expression. 

This will filter out all parent documents that match the query. The current mechanism was returning the parent document if there was another entry in the same nested array that did/didn't match the query.

I don't believe this fully fixes everything.. in working on this I realized that there is a filtered aggregation that I need to inject my query parser into so that nested fields are handled correctly.

I don't know if this fully fixes your issue. Please test and let me know.

**Comment by Tehtehteh** [comment]
@ppadovani, tested this fork: [](https://github.com/homeaway/kibana/tree/nestedSupport-4.5.4)
 Seems like it still builds wrong queries. What I tried to do:
1) In visualization tab create vertical bar chart.
2) Chosen my index.
3) Y-axis is count metric
4) Added X-axis buckets Split Bars, set them to Terms - > user_id
5) Added sub-buckets, Split Bars, Sub-aggregations is Filter-type and query is
users.won = 1. It shows bars which represents count of users which are in same document with any user who won. What I wanted to do: create bars which represents count of victories of each users.
Tried to use these queries:
`* AND users.won=1` -  this one makes field red and signals about error I'm not sure why.
`EXISTS users.won=1` - this one result in wrong results as described.
`users.won=1` - wrong results again.

**Comment by ppadovani** [comment]
Thanks for the reproduction steps. As I stated in my last comment, this particular piece was the one that I needed to still fix. I will post back when I have a better idea of the difficulty.

**Comment by Tehtehteh** [comment]
Great news. I will test it ASAP.

**Comment by ppadovani** [comment]
Ok... I believe I have aggregation filters for nested fields working correctly. 

NOTE: This may not work for very complex queries in the filter. For simple field filters like users.user_won=1 it should work. It depends on the query. I will continue to think about how to refine the solution to support more complex queries.

please test.

**Comment by Tehtehteh** [comment]
@ppadovani can I contact you via e-mail ?

**Comment by ppadovani** [comment]
@Tehtehteh I get emails for each update you post here, I'm not sure why you would need my email. Can you provide a reason? 

Also, please take a look at: https://github.com/elastic/elasticsearch/issues/11749

Looks like there was a bug that was resolved just this last July related to nested aggregation filters , I would guess it is fixed in 5.X.

**Comment by Tehtehteh** [comment]
@ppadovani, I just wanted to say that unfortunately I will be able to test this on Monday, because of PC issues.
Yeah, I saw this issue, this mapping is almost identical to mine.

**Comment by Tehtehteh** [comment]
@ppadovani, I tested newest fork and unfortunately results are still wrong.
 Query is [](http://www.jsoneditoronline.org/?id=42d897b5005e1966ee0cb1168963c43e).

**Comment by ppadovani** [comment]
The query looks correct... both aggs are within the same nested agg scope... as they have the same nested path... can you craft a query that produces the correct results?

**Comment by ppadovani** [comment]
I updated your json query here: 
http://www.jsoneditoronline.org/?id=42d897b5005e1966ee0cb1168963c43e

It now has what I am generating.. can you please run the query manually against your data to confirm if it works?

**Comment by Tehtehteh** [comment]
When I run with CURL:
http://www.jsoneditoronline.org/?id=90a422b48b0c37d67d4d134579c4de51

**Comment by ppadovani** [comment]
ok.. I think I know exactly what you are looking for.. this query works they way I think you intend:

`{
  "size": 0,
  "query": {
    "query_string": {
      "analyze_wildcard": true,
      "query": "*"
    }
  },
  "aggs": {
    "nested_2": {
      "nested": {
        "path": "users"
      },
      "aggs": {
        "2": {
          "terms": {
            "field": "users.user_id",
            "size": 5,
            "order": {
              "_count": "desc"
            }
          },
          "aggs": {
            "3": {
              "filter": {
                "term": {
                  "users.user_won": 1
                }
              }
            }
          }
        }
      }
    }
  }
}`

As near as I can tell, there isn't a way in Kibana to add a filter like that. The filters aggregation does not work in that manner... What you want is a 'filter' NOT 'filters' aggregation.  What would need to exist would be a 'filter query' text box, maybe under advanced of the bucket, that allows for a query to be entered. This would then inject a filter aggregation.

This is possible, but begins to diverge this fork from the main Kibana fork feature wise... I will think on it.

**Comment by ppadovani** [comment]
The other thing you could do is:
![image](https://cloud.githubusercontent.com/assets/11234684/21358627/ec21473a-c69e-11e6-8574-cfa896c91bc8.png)

Which yields a bar chart where you have wins vs losses for each user.

**Comment by ppadovani** [comment]
Please reopen if this is still an issue.
